project:
  type: website
  output-dir: docs

website:
  title: "Madi Schartz"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: file/path/to/myCV.pdf
        text: Resume
        target: _blank # opens link (or page) in a new browser tabResume.qmd
      - CSUProjects.qmd
      - icon: github # add icons as navbar buttons
        href: https://github.com/madi-schartz
        target: _blank

page-footer:
    background: light # or `dark`
    left: Copyright 2025, Madi Schartz


format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

