---
title: "Projects"
format: html
---

In the Spring of 2025 I took the course ESS 330 Quantitative Reasoning class based in R. I learned how to use RStudio and GitHub to code projects like this one! Scroll down to explore my other projects I did throughout the semester.

## [My GitHub Repo for Building this Website](https://github.com/madi-schartz/Madi-Schartz.github.io)

-   In this assignment we built a static users site with Github Pages

-   I learned how to fork pages from Mikes GitHub account to mine to be able to use in this project.

-   I gained the skills of using qmd and yml files to organize content for the webpage I created.

-   I learned how to maintain workflows using Quarto and GitHub in a way that can communicate several documents.

-   I learned how to write in Quarto and in code to create a cohesive website.

-   I gained confidence in my technical skills. I would have never thought I would be able to produce a working website with so many moving parts!

## [Lab 3: COVID-19](https://madi-schartz.github.io/csu-ess-lab3/lab-03.html)

-   I learned how the ability to have access to open data is extremely important for equitable exposure within environmental science.

-   I got to practice my data wrangling skills using a real-world data-set about COVID cases through the New York Times. 

## [Lab 4: Statistics in R](https://madi-schartz.github.io/Lab-4-LTER-Network-Data/docs/lab4.html)

-   I got to practice my skills using coding to run through basic statistical tests in like chi-square, t-tests, and correlation tests. 

-   We were given examples from our assignment instructions that helped me reproduce the same statistical tests on the Long-Term Ecological Research (LTER) Network data sets. 

## [Lab 5: Final Project- Proposals](https://snauman4.github.io/ESS330_FinalProject/)

-   This lab was our first work done, in our group of three, for our final project. We finalized our title, justification, research objective and hypothesis, proposed methods, and our expected outcomes. 

-   We decided to focus on water quality analysis on rivers within the Southwestern River Basins. We additionally wanted to look to see if there is any difference in water quality between river sites within protected areas vs unprotected areas. 

## [Lab 6: ML Workflows](https://madi-schartz.github.io/Lab6/lab6.html)

-   This is the lab where I was introduced to the tidymodels package, meant for predictive modeling, which was so helpful!

-   I got to go through the coding process of doing an exploratory data analysis on our CAMELS data-set to see how mean stream flow looks across a map of the United States.

-   I have taken a GIS course so this lab felt like a connection of my background knowledge of GIS and now learning new skills in coding within R Studio which was a lot of fun!

## [Lab 7: Final Project- Intro/Methods Draft](https://snauman4.github.io/ESS330_FinalProject/)

-   We were given feedback on our lab 5 which was our final project proposals and fixed based off of the feedback. 

-   In addition to this we wrote the Intro and Method draft where we found two sites within the Cache la Poudre river basin system, one being in an unprotected site and the other being in a protected site. 

## [Lab 8: ML Tuning](https://madi-schartz.github.io/Lab8/Lab8.html)

-   This lab presented a sharp learning curve for me but once I got it everything was smooth! It was about taking the "Whole Game Plan" about machine learning and applying it to the CAMELS data-set we have used in prior labs.

-   The concept I am most proud of learning was how to properly clean data and split it to then create a recipe that actually works! From there the re-sampling and the three candidate models was pretty straight forward for me. I really enjoy using the Random forests and Boosted trees models. 

## [Lab 9: Final Project- Results/Discussion Draft](https://snauman4.github.io/ESS330_FinalProject/)

-    We were given feedback on our lab 7, which was our final introduction and method sections, and fixed based off of the feedback.

-   We added 8 more sites, 4 for protected and 4 for unprotected areas, in states ranging throughout the Southwestern River Basins. This was challenging as data was limited and not consistent for all the water quality measurements we were looking for. I learned how to persevere through challenges and we got through it with amazing graphs and figures! 

## [Lab 10: Distances and Projections](https://madi-schartz.github.io/Lab10/lab10.html#lab-10-distances-and-projections)

-   I have had a lot of fun dealing with spatial data, as I have mentioned above, it creates this connection in my mind relating back to my time in GIS. 

-   I was able to have clean maps that show the equidistant between the Mexico and Canada borders and highlight the danger zones within 100-mile border zone from our National borders. 

## [Lab 11: Final Project: Lightning Talks](https://snauman4.github.io/ESS330_FinalProject/)

-   This is our final project that we submitted to our assignment and gave a presentation on.  We were given our last feedback on our lab 9, which was our final results and discussion sections, and fixed based off of the feedback.

-  We added in a map that highlighted all of our river sites, added in a decomposition time graph, and standardized our data by size of river basin that way we are are to compare apples to apples. 

## Look at how high quality my work is and how far my progress throughout the semester has gone!
