---
title: "Resume"
output: pdf_document
---

# Welcome to my Resume Page :)

Below is my resume or you can download the pdf here [Natural Resources Resume 2025](file:///C:/Users/mads23/Documents/GitHub_2025/Madi-Schartz.github.io/resume.pdf).



Madison Schartz
Fort Collins, CO | (303) 921-6630 | Mmschartz04@gmail.com | www.linkedin.com/in/Madi-Schartz

HORTICULTURE | ENVIRONMENTAL SERVICES | SUSTAINABLE FOOD SYSTEMS

I am an emerging, highly-organized leader eager to get hands-on experience positively impacting our community. As an outgoing person, I love to connect with different types of people in all types of environments. I am passionate about horticulture, sustainable food systems, ecosystems, and conservation work. I strive to make a difference in strengthening our community ties to the environment with values in making our space inclusive and equitable.

PERSONAL SKILLS:

❖ Conflict resolution
❖ Interpersonal and communication skills
❖ Adaptable

CERTIFICATIONS:

❖ IRB Social, Humanistic, Behavioral Research
❖ TIPS


EDUCATION

Bachelor of Science in Ecosystem Science and Sustainability August 2023 - May, 2025
Colorado State University, Fort Collins, CO 3.5 GPA
➢ Participate in ENGAGE scholars, Zero Waste Club, and ESS club
➢ Study Abroad : Sustainable Food Systems in Chocolate, Costa Rica March 2025


COMMUNITY IMPACT INITIATIVES

Youth Community Garden Project

❖ Led and coordinated a twelve person volunteer trip to Moab, Utah through BreaksAway to aid in flood
restoration at the Youth Community Garden.
Rocky Mountain Restoration

❖ Worked with National Park Service through ENGAGE scholars to aid in riparian restoration by planting alder
and willow trees in Rocky Mountain National Park to restore the habitat for the beaver population.


WORK EXPERIENCE

Gardens on Spring Creek, Fort Collins, CO — Horticulture Intern, Gardener        May 2024 -Dec 2024
➢ Successfully followed through with organic gardening methods.
➢ Grew 6,436 lbs of food to donate to the Larimer County Food Bank.
➢ Responsible for the horticulture work in the 3 acres of Garden of Eatin’ from soil prep to harvest.
➢ Coordinated and led two volunteer groups of 10+ people biweekly.

Olive Garden, Fort Collins, CO — Server                                          May 2023 -May 2024
➢ Displayed enthusiasm and promoted excellent guest service to guests.
➢ Successfully increased referrals, walk-in business, sales numbers.
➢ Carried out opening, closing, and shift change responsibilities to keep the restaurant working efficiently.

Ghost Towns, Bozeman, MT — Barista                                              Jan 2023 - May 2023
➢ Worked with local composting sites and farmers to repurpose used coffee grounds.
➢ Cultivated warm relationships with regular customers.
➢ Created stronger bonds with the community in a sustainable way
